
export const UPDATE_AUTH = "UPDATE_AUTH";
export const LOGOUT = "LOGOUT";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CHANGE_FILTER = "CHANGE_FILTER";
export const CHANGE_PAGINATION = "CHANGE_PAGINATION";
export const RESET_FILTERS = "RESET_FILTERS";
export const RESET_PAGINATION = "RESET_PAGINATION";
export const GET_MOVIES = "GET_MOVIES";
export const TOGGLE_LOADER = "TOGGLE_LOADER";
export const TOGGLE_LOADER_VIDEOS = "TOGGLE_LOADER_VIDEOS";
export const TOGGLE_LOADER_CREDITS = "TOGGLE_LOADER_CREDITS";
